#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: intellij
# Description:
# 	Defines ...
# 	nextline
###############################################################################

#
# Template for new module creation.
# Substitute the new module name for 'intellij'
# %s/oldname/newname/gc

__intellij_dependencies=( 'mbe' )
__intellij_functions=( '_intellij_load' '_intellij_unload' '_intellij_setpath' '_intellij_info' '_intellij_complete' '_intellij_idea' 'idea' )
__intellij_aliases=( 'android-studio' 'clion' 'goland' 'intellij' )

_intellij_load ()
{
	DEBUG echo "intellij_load: enter"
	local module="intellij"

	# Load preferences
	source "${MODULES_DIR}/${module}/${module}.conf"

	# Configure module

	DEBUG echo "intellij_load: leave"
}

_intellij_unload ()
{
	local func
	for func in "${__intellij_functions[@]}"; do
		unset "${func}"
	done
	for als in "${__intellij_aliases[@]}"; do
		unalias "${als}"
	done
	return 0
}

_intellij_setpath ()
{
	DEBUG echo "intellij_setpath: enter"

  export JETBRAINS_TOOLBOX_DIR="${HOME}/Applications/JetBrains Toolbox"
  # Android Studio.app
  # CLion.app
  # DataGrip.app
  # GoLand.app
  # IntelliJ IDEA Ultimate.app
  # PhpStorm.app
  # PyCharm Professional.app
  # WebStorm.app

	if [ -d "${JETBRAINS_TOOLBOX_DIR}" ]; then
	  alias android-studio='open -a "${JETBRAINS_TOOLBOX_DIR}/Android Studio.app"'
	  alias clion='open -a "${JETBRAINS_TOOLBOX_DIR}/CLion.app"'
	  alias datagrip='open -a "${JETBRAINS_TOOLBOX_DIR}/DataGrip.app"'
	  alias goland='open -a "${JETBRAINS_TOOLBOX_DIR}/GoLand.app"'
	  alias intellij='open -a "${JETBRAINS_TOOLBOX_DIR}/IntelliJ IDEA Ultimate.app"'
	  alias phpstorm='open -a "${JETBRAINS_TOOLBOX_DIR}/PhpStorm.app"'
	  alias pycharm='open -a "${JETBRAINS_TOOLBOX_DIR}/PyCharm Professional.app"'
	  alias webstorm='open -a "${JETBRAINS_TOOLBOX_DIR}/WebStorm.app"'
  fi
  DEBUG echo "intellij_setpath: leave"
}

_intellij_info ()
{
  DEBUG echo "intellij_info: leave"
}

_intellij_idea ()
{
	# Opens a repo by name in IntelliJ IDEA.
	# Usage: mbe intellij idea <repo-name> (substring match, searched across
	# INTELLIJ_IDEA_SEARCH_ROOTS up to 4 levels deep; only matches git repos.)
	local query="$1"
	if [ -z "${query}" ]; then
		echo "Usage: mbe intellij idea <repo-name>" >&2
		return 1
	fi

	local matches=( )
	local root dir
	for root in "${INTELLIJ_IDEA_SEARCH_ROOTS[@]}"; do
		[ -d "${root}" ] || continue
		while IFS= read -r dir; do
			[ -e "${dir}/.git" ] && matches+=("${dir}")
		done < <(find "${root}" -mindepth 1 -maxdepth 4 -type d -iname "*${query}*" 2>/dev/null | sort)
	done

	if [ "${#matches[@]}" -eq 0 ]; then
		echo "No git repo matching '${query}' found." >&2
		return 1
	elif [ "${#matches[@]}" -eq 1 ]; then
		echo "Opening ${matches[0]}"
		open -na "${INTELLIJ_IDEA_APP}" --args "${matches[0]}"
	else
		echo "Multiple matches -- pick one:"
		local i
		for i in "${!matches[@]}"; do
			echo "  $(( i + 1 ))) ${matches[$i]}"
		done
		local choice
		printf "Enter number: "
		read -r choice </dev/tty
		if [[ "${choice}" =~ ^[0-9]+$ ]] && [ "${choice}" -ge 1 ] && [ "${choice}" -le "${#matches[@]}" ]; then
			echo "Opening ${matches[$(( choice - 1 ))]}"
			open -na "${INTELLIJ_IDEA_APP}" --args "${matches[$(( choice - 1 ))]}"
		else
			echo "Invalid selection." >&2
			return 1
		fi
	fi
}

idea () { _intellij_idea "$@"; }

_intellij_complete()
{
	COMPREPLY=( )
	return 0
}
