#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: rar
# Description:
# 	Defines ...
# 	nextline
###############################################################################

#
# Template for new module creation.
# Substitute the new module name for 'rar'
# %s/rar/newname/gc

__rar_dependencies=( 'mbe' )
__rar_functions=( '_rar_load' '_rar_unload' '_rar_setpath' '_rar_usage' )

_rar_load ()
{
	DEBUG echo "_rar_load: enter"
	local module="rar"

	# Load preferences
	
	# Configure module

	DEBUG echo "_rar_load: leave"
}

_rar_unload ()
{
	local func
	for func in "${__rar_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_rar_setpath ()
{
	# RAR Tooling, 32-bit only at present
	if [ -x "${TOOLSPATH32}/rar/rar" ]; then
		PATH="${TOOLSPATH32}/rar:${PATH}"
	fi
}

_rar_usage ()
{
	echo "no usage info"
}
