#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: rar
# Description:
# 	Defines ...
# 	nextline
###############################################################################

rar_dependencies=( 'mbe' )
rar_functions=( 'rar_load' 'rar_unload' 'rar_setpath' 'rar_usage' )

rar_load ()
{
	DEBUG echo "rar_load: enter"
	local module="rar"

	# Load preferences
	
	# Configure module

	DEBUG echo "rar_load: leave"
}

rar_unload ()
{
	local func
	for func in "${rar_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

rar_setpath ()
{
	# RAR Tooling, 32-bit only at present
	if [ -x "${TOOLSPATH32}/rar/rar" ]; then
		PATH="${TOOLSPATH32}/rar:${PATH}"
	fi
}

rar_usage ()
{

}
