#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: xcode
# Description:
# 	Defines ...
# 	nextline
###############################################################################

#
# Template for new module creation.
# Substitute the new module name for 'xcode'
# %s/xcode/newname/gc

xcode_dependencies=( 'mbe' )
xcode_functions=( 'xcode_load' 'xcode_unload' 'xcode_setpath' 'xcode_usage' )

xcode_load ()
{
	DEBUG echo "xcode_load: enter"
	local module="xcode"

	# Load preferences
	
	# Configure module

	DEBUG echo "xcode_load: leave"
}

xcode_unload ()
{
	local func
	for func in "${xcode_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

xcode_setpath ()
{
	if [ -e /Developer/usr ]; then
		PATH=/Developer/usr/bin:$PATH
		LD_LIBRARY_PATH=/Developer/usr/lib:$LD_LIBRARY_PATH
		MANPATH=/Developer/usr/share/man:$MANPATH
	fi
}

xcode_usage ()
{
	echo "XCode module has no special commands or configuration at this time"
}
