#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

sunstudio_dependencies=( 'mbe' )
sunstudio_functions=( 'sunstudio_load' 'sunstudio_unload' 'sunstudio_setpath' 'sunstudio_usage' )

sunstudio_load ()
{
	DEBUG echo "sunstudio_load: enter"
	local module="sunstudio"

	# Load preferences
	
	# Configure module

	DEBUG echo "sunstudio_load: leave"
}

sunstudio_unload ()
{
	local func
	for func in "${sunstudio_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

sunstudio_setpath ()
{
	# For Sun Studio 11 on Linux
	if [ -e /usr/sun/sunstudio11 ]; then
		SPRO_NETBEANS_HOME=/usr/sunstudio11/netbeans/3.5V11/bin
		export SPRO_NETBEANS_HOME
		PATH=/usr/sun/sunstudio11/bin:$PATH
		LD_LIBRARY_PATH=/usr/sun/sunstudio11/lib:$LD_LIBRARY_PATH
		MANPATH=/usr/sun/sunstudio11/man:$MANPATH
	fi

	# For the Sun Studio 11 on Solaris
	# Docs at .../sunstudio11/docs/index.html
	if [ -e /compilers/v11 ]; then
		SPRO_NETBEANS_HOME=/compilers/v11/netbeans/3.5V11/bin
		export SPRO_NETBEANS_HOME
		PATH=/compilers/v11/SUNWspro/bin:/compilers/v11/jdk/j2se/bin${PATH:+:}${PATH}
		LD_LIBRARY_PATH=/compilers/v11/SUNWspro/lib:/compilers/v11/netbeans/3.5V11/lib:/compilers/v11/jdk/j2se/lib:$LD_LIBRARY_PATH
		MANPATH=/compilers/v11/SUNWspro/man:/compilers/v11/jdk/j2se/man:${MANPATH:=/usr/share/man}
	fi
}

sunstudio_usage ()
{

}
