#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: sbin
# Description:
# 	Defines ...
# 	nextline
###############################################################################

__sbin_dependencies=( 'mbe' )
__sbin_functions=( '_sbin_load' '_sbin_unload' '_sbin_setpath' '_sbin_usage' '_sbin_complete' )

_sbin_load ()
{
	DEBUG echo "_sbin_load: enter"
	local module="sbin"

	# Load preferences
	
	# Configure module

	DEBUG echo "_sbin_load: leave"
}

_sbin_unload ()
{
	local func
	for func in "${__sbin_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_sbin_setpath ()
{
	# Adds in sbin paths as there are many useful sysadminly tools there
	local sbin_paths=("/sbin" "/usr/sbin" "/usr/local/sbin" "/opt/local/sbin")
	for i in "${sbin_paths[@]}"; do
	if [ -d "${i}" ]; then
		PATH="${i}:${PATH}"
	fi
	done
}

_sbin_usage ()
{
	echo "no usage info"
}

_sbin_complete()
{
	COMPREPLY=( )
	return 0
}
