#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: sbin
# Description:
# 	Defines ...
# 	nextline
###############################################################################

sbin_dependencies=( 'mbe' )
sbin_functions=( 'sbin_load' 'sbin_unload' 'sbin_setpath' 'sbin_usage' )

sbin_load ()
{
	DEBUG echo "sbin_load: enter"
	local module="sbin"

	# Load preferences
	
	# Configure module

	DEBUG echo "sbin_load: leave"
}

sbin_unload ()
{
	local func
	for func in "${sbin_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

sbin_setpath ()
{
	# Adds in sbin paths as there are many useful sysadminly tools there
	sbin_paths=("/sbin" "/usr/sbin" "/usr/local/sbin")
	for i in "${sbin_paths[@]}"; do
	if [ -d "${i}" ]; then
		PATH="${i}:${PATH}"
	fi
	done
}

sbin_usage ()
{

}
