#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: openwin
# Description:
# 	Defines ...
# 	nextline
###############################################################################

__openwin_dependencies=( 'mbe' )
__openwin_functions=( '_openwin_load' '_openwin_unload' '_openwin_setpath' '_openwin_usage' '_openwin_complete' )

_openwin_load ()
{
	DEBUG echo "_openwin_load: enter"
	local module="openwin"

	# Load preferences
	
	# Configure module

	DEBUG echo "_openwin_load: leave"
}

_openwin_unload ()
{
	local func
	for func in "${__openwin_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_openwin_setpath ()
{
	if [ -d "/usr/openwin/bin/" ]; then
		PATH="/usr/openwin/bin:${PATH}"
	fi
}

_openwin_usage ()
{
	echo "no usage info"
}

_openwin_complete()
{
	COMPREPLY=( )
	return 0
}
