#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

#---------------------------------------------
# ------ ClearCase Tools Related -------------
#---------------------------------------------

clearcase_dependencies=( 'mbe' )
clearcase_functions=( 'clearcase_load' 'clearcase_unload' 'clearcase_setpath' 'clearcase_usage' 'ct' 'csv' 'prefiff' 'myviews' 'codir' )

clearcase_load ()
{
	DEBUG echo "clearcase_load: enter"
	local module="clearcase"

	# Load preferences
	
	# Configure module

	DEBUG echo "clearcase_load: leave"
}

clearcase_unload ()
{
	local func
	for func in "${clearcase_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

clearcase_setpath ()
{
	# ClearCase & ClearQuest Tools
	if [ -e /usr/atria/bin ]; then
		CCTOOLS_PATH=/usr/atria/bin:/atria_release/cmbin/mergescripts
		PATH=$CCTOOLS_PATH:$PATH
	fi
}

clearcase_usage ()
{
	echo "no usage info"
}

ct ()
{
	cleartool $@
}

csv ()
{
	cleartool setview $@
}

prediff ()
{
	cleartool diff -diff -pre $@
}

myviews ()
{
	cleartool lsview $@ |grep ${USER}
}

codir ()
{
	usage="Usage: codir [-p <path to checkout under>] [-c <checkout comment>] [-i] [-d]"
	checkout_path=`pwd`
	xargs_interactive=0
	debug=0

	while getopts ":p:c:id" option
	do
		case $option in
			p  ) checkout_path=$OPTARG ;;
			c  ) checkout_comment="${OPTARG}";;
			i  ) xargs_interactive=1;;
			d  ) debug=1;;
			h  ) echo $usage;;
			\? ) echo $usage
			     OPTIND=1
			     return;;
			*  ) echo $usage
			     OPTIND=1
			     return;;
		esac
	done
	# reset OPTIND to 1
	OPTIND=1

	if [ $xargs_interactive -eq 0 ]; then
		xargs_args="-i"
	else
		xargs_args="-pi"
	fi

	if [ $debug -eq 1 ]; then
		echo "checkout_path=$checkout_path"
		echo "checkout_comment=$checkout_comment"
		echo "xargs_args=$xargs_args"
	fi

	if [ -z "$checkout_comment" ]; then
		find "$checkout_path" | xargs "$xargs_args" cleartool -nc {}
	else
		find "$checkout_path" | xargs "$xargs_args" cleartool -c "$checkout_comment" {}
	fi
}

