#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

clearcase_dependencies=( 'mbe' )
clearcase_functions=( 'clearcase_load' 'clearcase_unload' 'clearcase_setpath' 'clearcase_usage' )

clearcase_load ()
{
	DEBUG echo "clearcase_load: enter"
	local module="clearcase"

	# Load preferences
	
	# Configure module

	DEBUG echo "clearcase_load: leave"
}

clearcase_unload ()
{
	local func
	for func in "${clearcase_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

clearcase_setpath ()
{
	# ClearCase & ClearQuest Tools
	if [ -e /usr/atria/bin ]; then
		CCTOOLS_PATH=/usr/atria/bin:/atria_release/cmbin/mergescripts
		PATH=$CCTOOLS_PATH:$PATH
	fi
}

clearcase_usage ()
{
	echo "no usage info"
}
