#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent: 

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

############################################################
# Module: colors
# Description:
# 	Defines various human-friendly names to refer to shell 
# 	color escape-sequences.
############################################################

__colors_functions=( '_colors_load' '_colors_unload' '_colors_setpath' '_colors_define' '_colors_undefine' '_colors_complete' )

_colors_load ()
{
	DEBUG echo "_colors_load: enter"
	local module="colors"
	# Load preferences
	
	# Configure module
	_colors_define
	DEBUG echo "_colors_load: leave"
}

_colors_unload ()
{
	_colors_undefine
	local func
	for func in "${__colors_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_colors_setpath ()
{
	local module="colors"
}

_colors_define ()
{
	# color_name='\[\033[ modifier; color_code m\]'
	# Modifiers
	# 0 = default          1 = bold
	# 4 = underlined       5 = flashing text
	# 7 = reverse field
	__colors_restore='\[\033[00m\]'
	__colors_black='\[\033[00;30m\]'
	__colors_firebrick='\[\033[00;31m\]'
	__colors_red='\[\033[01;31m\]'
	__colors_forest='\[\033[00;32m\]'
	__colors_green='\[\033[01;32m\]'
	__colors_brown='\[\033[00;33m\]'
	__colors_yellow='\[\033[01;33m\]'
	__colors_navy='\[\033[00;34m\]'
	__colors_blue='\[\033[01;34m\]'
	__colors_purple='\[\033[00;35m\]'
	__colors_magenta='\[\033[01;35m\]'
	__colors_cadet='\[\033[00;36m\]'
	__colors_cyan='\[\033[01;36m\]'
	__colors_gray='\[\033[00;37m\]'
	__colors_white='\[\033[01;37m\]'
	__colors_std="${__colors_white}"
	__colors_red_back='\[\033[00;41m\]'
	__colors_green_back='\[\033[00;42m\]'
	__colors_orange_back='\[\033[00;43m\]'
	__colors_blue_back='\[\033[00;44m\]'
	__colors_purple_back='\[\033[00;45m\]'
	__colors_cyan_back='\[\033[00;46m\]'
	__colors_grey_back='\[\033[00;47m\]'
}

############################
# ##### UNSET colors ##### #
############################
_colors_undefine ()
{
 unset __colors_restore     \
       __colors_black       \
       __colors_firebrick   \
       __colors_red         \
       __colors_forest      \
       __colors_green       \
       __colors_brown       \
       __colors_yellow      \
       __colors_navy        \
       __colors_blue        \
       __colors_purple      \
       __colors_magenta     \
       __colors_cadet       \
       __colors_cyan        \
       __colors_gray        \
       __colors_white       \
       __colors_std         \
       __colors_usr         \
			 __colors_red_back    \
			 __colors_green_back  \
			 __colors_orange_back \
			 __colors_blue_back   \
			 __colors_purple_back \
			 __colors_cyan_back   \
			 __colors_grey_back
}


_colors_complete()
{
	COMPREPLY=( )
	return 0
}

