#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

ibmxlc_dependencies=( 'mbe' )
ibmxlc_functions=( 'ibmxlc_load' 'ibmxlc_unload' 'ibmxlc_setpath' 'ibmxlc_usage' )

ibmxlc_load ()
{
	DEBUG echo "ibmxlc_load: enter"
	local module="ibmxlc"

	# Load preferences
	
	# Configure module

	DEBUG echo "ibmxlc_load: leave"
}

ibmxlc_unload ()
{
	local func
	for func in "${ibmxlc_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

ibmxlc_setpath ()
{
	# For the IBM XLC/XLC++ Compiler on PS3/CBE
	if [ -e /opt/ibmcmp/xlc/8.2 ]; then
		PATH=/opt/ibmcmp/xlc/8.2/bin:$PATH
		MANPATH=/opt/ibmcmp/xlc/8.2/man/en_US:$MANPATH
	fi
}

ibmxlc_usage ()
{
	echo "no usage info"
}
