#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

__maven_dependencies=( 'mbe' 'platform' 'utils' 'java' )
__maven_functions=( _maven_load _maven_unload _maven_setpath _maven_usage _maven_env _maven_config _maven_list _maven_listVersions _maven_complete )

# Environment Variables:
# MAVEN_PRODUCT
# MAVEN_PRODUCT_VERSION
# MAVEN_PRODUCT_SUBDIR
# MAVEN_JAVA_CREATOR
# MAVEN_JAVA_VERSION
# MAVEN_JAVA_BITS

_maven_load ()
{
	DEBUG echo "_maven_load: enter"
	# Load module dependencies
	_mbe_loadModules "${__maven_dependencies[@]}"

	local module="maven"
	# Load preferences file
	source "${MODULES_DIR}/${module}/${module}.conf"

	# Specify the default Eclipse product to be used
	MAVEN_PRODUCT=${MAVEN_PRODUCT:=apache-maven}
	MAVEN_PRODUCT_VERSION=${MAVEN_PRODUCT_VERSION:=2.2.1}
	
	# Specify the default Java to be used when running Eclipse
	MAVEN_JAVA_CREATOR=${MAVEN_JAVA_CREATOR:=IBM}
	MAVEN_JAVA_VERSION=${MAVEN_JAVA_VERSION:=1.5.0}
	MAVEN_JAVA_BITS=${MAVEN_JAVA_BITS:=32}

	DEBUG echo "_maven_load: leave"
	return 0

}

_maven_unload ()
{
	local module="maven"
	local func
	for func in "${__maven_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_maven_setpath ()
{
	local module="maven"

	if [ -e "${MAVEN_HOME}" ]; then
		PATH="${MAVEN_HOME}/bin:${PATH}"
		#CLASSPATH="${MAVEN_HOME}/lib:${CLASSPATH}"
		export MAVEN_OPTS="-Xms128m -Xmx512m"
		export JAVA_HOME
	fi
}

_maven_usage ()
{
	local module="maven"
}

_maven_env ()
{
	echo "MAVEN_HOME=${MAVEN_HOME}"
	echo "--------------------------------------------------------------------------------"
	echo "MAVEN_PRODUCT=${MAVEN_PRODUCT}"
	echo "MAVEN_PRODUCT_VERSION=${MAVEN_PRODUCT_VERSION}"
	echo "MAVEN_JAVA_CREATOR=${MAVEN_JAVA_CREATOR}"
	echo "MAVEN_JAVA_VERSION=${MAVEN_JAVA_VERSION}"
	echo "MAVEN_JAVA_BITS=${MAVEN_JAVA_BITS}"
}

_maven_config ()
{
	local module="maven"

	usage ()
	{
		echo "Usage: maven_config [-p <product>] [-v <version>] [-c <java_creator>] [-j <java_version>] [-b <java_bits>]"
		echo "	Configures a reasonable environment and executes the Eclipse version specified."
	}


	# parse arguments with getopts
	# reset getopts state variables
	unset print_usage
	while getopts "p:v:c:j:b:h" option
	do
		case $option in
			p  ) MAVEN_PRODUCT=$OPTARG;;
			v  ) MAVEN_PRODUCT_VERSION=$OPTARG;;
			c  ) MAVEN_JAVA_CREATOR=$OPTARG;;
			j  ) MAVEN_JAVA_VERSION=$OPTARG;;
			b  ) MAVEN_JAVA_BITS=$OPTARG;;
			h  ) print_usage="1";;
			\? ) print_usage="1";;
			*  ) print_usage="1";;
		esac
	done
	OPTIND=1 # Reset OPTIND
	
	if [[ "$print_usage" == 1 ]]; then
		usage
		return 0
	fi

	MAVEN_SUBDIR="${MAVEN_PRODUCT}/${MAVEN_PRODUCT_VERSION}" # The path under TOOLSPATH where the product can be found

	# Define MAVEN_HOME
	MAVEN_TOOLSPATH="${TOOLSPATHGENERIC}"
	MAVEN_HOME="${MAVEN_TOOLSPATH}/${MAVEN_SUBDIR}"

	# Export key variables
	export MAVEN_HOME

	# Check that MAVEN_HOME exists and is a directory
	if [ ! -d "$MAVEN_HOME" ]; then
		echo "ERROR: ${MAVEN_PRODUCT} does not exist at ${MAVEN_HOME}"
		MAVEN_HOME=""
		return 1
	fi
}

_maven_list()
{
	usage ()
	{
		echo "Usage: _maven_list <versions>"
	}

	case "$1" in
	versions)
		_maven_listVersions $2
		;;
	*)
		echo "Unrecognized option"
		return 1
		;;
	esac
}

_maven_listVersions ()
{
	local versions

	usage ()
	{
		echo "Usage: _maven_listVersions [-p <product>]"
		echo " Searches and lists the available Eclipse versions for a particular product."
	}

	# parse arguments with getopts
	# reset getopts state variables
	unset print_usage
	while getopts "p:b:h" option
	do
		case $option in
			p  ) SEARCH_PRODUCT=$OPTARG;;
			h  ) print_usage="1";;
			\? ) print_usage="1";;
			*  ) print_usage="1";;
		esac
	done
	OPTIND=1 # Reset OPTIND
	
	if [[ "$print_usage" == 1 ]]; then
		usage
		return 0
	fi

	SEARCH_PRODUCT=${SEARCH_PRODUCT:=${MAVEN_PRODUCT}}
	SEARCH_PATH="${TOOLSPATHGENERIC}/${SEARCH_PRODUCT}"

	declare -a versions=( $(find_eregex ${SEARCH_PATH} -maxdepth 1 -regex '.*/[0-9]+\.[0-9]+\.[0-9]+' | trimdirs | sort) )

	#'.*[0-9]+\.[0-9]+_[a-z0-9A-Z]+_[a-z0-9A-Z]+'

	echo "${versions[@]}"
}

_maven_complete()
{
	local opts
	COMPREPLY=( )
	opts="config env list"

	case "${prev}" in
		env)
			COMPREPLY=( )
			return 0
			;;
		list)
			local list_opts="versions"
			COMPREPLY=( $(compgen -W "${list_opts}" -- ${cur})  )
			return 0
			;;
		config)
			local config_opts="-p -v -j -c -b -n"
			COMPREPLY=( $(compgen -W "${config_opts}" -- ${cur})  )
			return 0
			;;
		esac

	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
	return 0
}
