#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

gcc_dependencies=( 'mbe' )
gcc_functions=( 'gcc_load' 'gcc_unload' 'gcc_setpath' 'gcc_usage' )

gcc_load ()
{
	DEBUG echo "gcc_load: enter"
	local module="gcc"

	# Load preferences
	
	# Configure module

	DEBUG echo "gcc_load: leave"
}

gcc_unload ()
{
	local func
	for func in "${gcc_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

gcc_setpath ()
{
	# Many GNU programs expect CPP to the the C++ compiler, not the C Pre-Processor, as is the case on Solaris.
	if [[ "${OSTYPE}" == solaris* ]]; then
		export CC=gcc
		# unset CPP
	elif [[ "${OSTYPE}" == linux* ]]; then
		export CC=gcc
		#export CPP=g++
	fi
}

gcc_usage ()
{
	echo "no usage info"
}
