#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: homebin
# Description:
# 	Adds the user's ~/home/bin folder into PATH
###############################################################################

__homebin_dependencies=( 'mbe' )

_homebin_load ()
{
	DEBUG echo "_homebin_load: enter"
	local module="homebin"

	# Load preferences
	
	# Configure module

	DEBUG echo "_homebin_load: leave"
}

_homebin_unload ()
{
	return 0
}

_homebin_setpath ()
{
	# Add in the bin folder in my home directory
	if [ -e "${HOME}/bin" ]; then
		PATH="${HOME}/bin:${PATH}"
	fi
}

_homebin_info ()
{
	echo -e "adds \$HOME/bin to \$PATH"
}

_homebin_complete()
{
	COMPREPLY=( )
	return 0
}
