#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: utils
# Description:
# 	Defines ...
# 	nextline
###############################################################################

#
# Template for new module creation.
# Substitute the new module name for 'utils'
# %s/utils/newname/gc

utils_dependencies=( 'mbe' 'platform' )
utils_functions=( 'utils_load' 'utils_unload' 'utils_setpath' 'utils_usage' 'trimdirs' )

utils_load ()
{
	DEBUG echo "utils_load: enter"
	local module="utils"

	# Load preferences
	
	# Configure module

	DEBUG echo "utils_load: leave"
}

utils_unload ()
{
	local func
	for func in "${utils_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

utils_setpath ()
{
	echo -ne ""
}

utils_usage ()
{
	echo -ne ""
}

trimdirs ()
{
	if (( $BSDARGS )); then
		sed -E 's/.*\///g'
	else
		sed -r 's/.*\///g'
	fi
}

find_eregex ()
{
	if (( $BSDARGS )); then
		find -E "${@}"
	else
		find "${@}"
		#find "${@}" -regextype "posix-extended"
	fi
}
