#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: homebrew
# Description:
# 	Defines ...
# 	nextline
###############################################################################

#
# Template for new module creation.
# Substitute the new module name for 'homebrew'
# %s/homebrew/newname/gc

__homebrew_dependencies=( 'mbe' )
__homebrew_functions=( '_homebrew_load' '_homebrew_unload' '_homebrew_setpath' '_homebrew_usage' '_homebrew_complete' )

_homebrew_load ()
{
	DEBUG echo "_homebrew_load: enter"
	local module="homebrew"

	# Load preferences
	
	# Configure module

	DEBUG echo "_homebrew_load: leave"
}

_homebrew_unload ()
{
	local func
	for func in "${__homebrew_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_homebrew_setpath ()
{
  if [ -f /usr/local/etc/profile.d/bash_completion.sh ]; then
      . /usr/local/etc/profile.d/bash_completion.sh
  fi
	if [ -f /usr/local/bin/hub ]; then
		alias git=hub
	fi
	if [ -f "/usr/libexec/java_home" ]; then
	  export JAVA_HOME=$(/usr/libexec/java_home)
	  export PATH="${JAVA_HOME}/bin:${PATH}"
	fi
	if [ -d "/usr/local/share/man" ]; then
		export MANPATH="/usr/local/share/man":${MANPATH}
	fi
}

_homebrew_usage ()
{
	echo -ne ""

}

_homebrew_complete()
{
	COMPREPLY=( )
	return 0
}
