#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: brlcad
# Description:
# 	Defines ...
# 	nextline
###############################################################################

__brlcad_dependencies=( 'mbe' )
__brlcad_functions=( '_brlcad_load' '_brlcad_unload' '_brlcad_setpath' '_brlcad_usage' '_brlcad_complete' )

_brlcad_load ()
{
	DEBUG echo "_brlcad_load: enter"
	local module="brlcad"

	# Load preferences
	
	# Configure module

	DEBUG echo "_brlcad_load: leave"
}

_brlcad_unload ()
{
	local func
	for func in "${__brlcad_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_brlcad_setpath ()
{
	# BRL-CAD
	if [ -e /usr/brlcad/bin ]; then
		PATH="/usr/brlcad/bin:${PATH}"
		LD_LIBRARY_PATH="/usr/brlcad/lib:${LD_LIBRARY_PATH}"
		MANPATH="/usr/brlcad/man:${MANPATH}"
	fi
}

_brlcad_usage ()
{
	echo "no usage info"
}

_brlcad_complete ()
{
	COMPREPLY=( )
	return 0
}
