#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: dia
# Description:
# 	Defines ...
# 	nextline
###############################################################################

__dia_dependencies=( 'mbe' )
__dia_functions=( '_dia_load' '_dia_unload' '_dia_setpath' '_dia_usage' '_dia_complete' )

_dia_load ()
{
	DEBUG echo "_dia_load: enter"
	local module="dia"

	# Load preferences
	
	# Configure module

	DEBUG echo "_dia_load: leave"
}

_dia_unload ()
{
	local func
	for func in "${__dia_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_dia_setpath ()
{
	# DIA
	if [ -e /opt/dia-0.96 ]; then
		PATH="/opt/dia-0.96/bin:${PATH}"
		MANPATH="/opt/dia-0.96/man:${MANPATH}"
	fi
}

__dia_usage ()
{
	echo "no usage info"
}

_dia_complete()
{
	COMPREPLY=( )
	return 0
}
