#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

scite_dependencies=( 'mbe' )
scite_functions=( 'scite_load' 'scite_unload' 'scite_setpath' 'scite_usage' )

scite_load ()
{
	DEBUG echo "scite_load: enter"
	local module="scite"

	# Load preferences
	
	# Configure module

	DEBUG echo "scite_load: leave"
}

scite_unload ()
{
	local func
	for func in "${scite_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

scite_setpath ()
{
	# For SciTE, Scintilla Text Editor
	if [ -e "${TOOLSPATH}/scite/1.75" ]; then
		PATH="${TOOLSPATH}/scite/1.75/bin:${PATH}"
	fi
}

scite_usage ()
{

}
