#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

__scite_dependencies=( 'mbe' )
__scite_functions=( '_scite_load' '_scite_unload' '_scite_setpath' '_scite_info' '_scite_compete')

_scite_load ()
{
	DEBUG echo "_scite_load: enter"
	local module="scite"

	# Load preferences
	
	# Configure module

	DEBUG echo "_scite_load: leave"
}

_scite_unload ()
{
	local func
	for func in "${__scite_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_scite_setpath ()
{
	# For SciTE, Scintilla Text Editor
	if [ -e "${TOOLSPATH}/scite/1.75" ]; then
		PATH="${TOOLSPATH}/scite/1.75/bin:${PATH}"
	fi
}

_scite_info ()
{
	echo "Configures the path to the SciTE editor"
}

_scite_complete()
{
	COMPREPLY=( )
	return 0
}
