#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: userid
# Description:
# 	Defines ...
# 	nextline
###############################################################################

#
# Template for new module creation.
# Substitute the new module name for 'userid'
# %s/userid/newname/gc

__userid_dependencies=( 'mbe' )
__userid_functions=( '_userid_load' '_userid_unload' '_userid_setpath' '_userid_info' 'ur' )

_userid_load ()
{
	DEBUG echo "_userid_load: enter"
	local module="userid"

	# Load preferences
	
	# Configure module

	DEBUG echo "_userid_load: leave"
}

_userid_unload ()
{
	local func
	for func in "${__userid_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_userid_setpath ()
{
	DEBUG echo -n ""
}

_userid_inf ()
{
	echo "Configures the Informix userid executable"
}

ur ()
{
	which userid &>/dev/null
	if [ "$?" -eq 0 ]; then
		userid root "$*"
	else
		sudo -u root "$*"
	fi
}

_userid_complete()
{
	COMPREPLY=( )
	return 0
}
