#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: userid
# Description:
# 	Defines ...
# 	nextline
###############################################################################

#
# Template for new module creation.
# Substitute the new module name for 'userid'
# %s/userid/newname/gc

userid_dependencies=( 'mbe' )
userid_functions=( 'userid_load' 'userid_unload' 'userid_setpath' 'userid_usage' 'ur' )

userid_load ()
{
	DEBUG echo "userid_load: enter"
	local module="userid"

	# Load preferences
	
	# Configure module

	DEBUG echo "userid_load: leave"
}

userid_unload ()
{
	local func
	for func in "${userid_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

userid_setpath ()
{
	DEBUG echo -n ""
}

userid_usage ()
{
	echo "no usage info"
}

ur ()
{
	userid root $@
}
