#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: netclient
# Description:
# 	Defines ...
# 	nextline
###############################################################################

netclient_dependencies=( 'mbe' )
netclient_functions=( 'netclient_load' 'netclient_unload' 'netclient_setpath' 'netclient_usage' )

netclient_load ()
{
	DEBUG echo "netclient_load: enter"
	local module="netclient"

	# Load preferences
	
	# Configure module

	DEBUG echo "netclient_load: leave"
}

netclient_unload ()
{
	local func
	for func in "${netclient_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

netclient_setpath ()
{
	# AT&T NetClient
	local netclientbindir="/opt/agns/bin"
	if [ -f "$netclientbindir" ]; then
		PATH="${netclientbindir}":"${PATH}"
	fi
}

netclient_usage ()
{
	echo "no usage info"
}
