#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: netclient
# Description:
# 	Defines ...
# 	nextline
###############################################################################

__netclient_dependencies=( 'mbe' )
__netclient_functions=( '_netclient_load' '_netclient_unload' '_netclient_setpath' '_netclient_usage' '_netclient_complete' )

_netclient_load ()
{
	DEBUG echo "_netclient_load: enter"
	local module="netclient"

	# Load preferences
	
	# Configure module

	DEBUG echo "_netclient_load: leave"
}

_netclient_unload ()
{
	local func
	for func in "${_netclient_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_netclient_setpath ()
{
	# AT&T NetClient
	local netclientbindir="/opt/agns/bin"
	if [ -f "$netclientbindir" ]; then
		PATH="${netclientbindir}":"${PATH}"
	fi
}

_netclient_usage ()
{
	echo "no usage info"
}

_netclient_complete()
{
	COMPREPLY=( )
	return 0
}
