#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

############################################################
# Module: Developer
# Description:
# 	Defines paths for the many tools used in program
# 	development.
############################################################

__developer_dependencies=( 'mbe' 'platform' )
__developer_functions=( '_developer_load' '_developer_unload' '_developer_setpath' )

_developer_load ()
{
	DEBUG echo "_developer_load: enter"
	# Load module dependencies
	_mbe_activateModules "${__developer_dependencies[@]}"
	local module="developer"
	# Load preferences file
	source "${MODULES_DIR}/${module}/${module}.conf"
	# Source the features specified in preferences file
	DEBUG echo "_developer_load: developer_features=${__developer_features[@]}"
	local feature
	for feature in "${__developer_features[@]}"; do
		source "${MODULES_DIR}/${module}/${feature}"
	done
	DEBUG echo "_developer_load: leave"
	return 0
}

_developer_unload ()
{
	local func
	for func in "${__developer_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_developer_setpath ()
{
	DEBUG echo "_developer_setpath: enter"
	local module="developer"
	DEBUG echo "_developer_setpath: developer_features=${__developer_features[@]}"
	local feature
	for feature in "${__developer_features[@]}"; do
		DEBUG echo ${module}_${feature}_setpath
		${module}_${feature}_setpath
	done
	DEBUG echo "_developer_setpath: leave"
	return 0
}

_developer_complete()
{
	COMPREPLY=( )
	return 0
}
