#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

__vim_dependencies=( 'mbe' 'platform' )

_vim_load ()
{
	DEBUG echo "_vim_load: enter"
	_mbe_activateModules "${__vim_dependencies[@]}"
	local module="vim"

	# Load preferences
	
	# Configure module

	DEBUG echo "_vim_load: leave"
}

_vim_unload ()
{
	return 0
}

_vim_setpath ()
{
	# Use custom version of vim in $TOOLSPATH/vim if available
	if [ -d "${TOOLSPATH}/vim" ]; then
		PATH="${TOOLSPATH}/vim/bin:${PATH}"
		MANPATH="${TOOLSPATH}/vim/man:${MANPATH}"
	fi
}

vim_info ()
{
	echo "Configures GNU ViM"
}

_vim_complete()
{
	COMPREPLY=( )
	return 0
}
