#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

vim_dependencies=( 'mbe' )
vim_functions=( 'vim_load' 'vim_unload' 'vim_setpath' 'vim_usage' )

vim_load ()
{
	DEBUG echo "vim_load: enter"
	local module="vim"

	# Load preferences
	
	# Configure module

	DEBUG echo "vim_load: leave"
}

vim_unload ()
{
	local func
	for func in "${vim_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

vim_setpath ()
{
	# Use custom version of vim in $TOOLSPATH/vim if available
	if [ -d "${TOOLSPATH}/vim" ]; then
		PATH="${TOOLSPATH}/vim/bin:${PATH}"
		MANPATH="${TOOLSPATH}/vim/man:${MANPATH}"
	fi
}

vim_usage ()
{
	echo "no usage info"
}
