#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

__cscope_dependencies=( 'mbe' )
__cscope_functions=( '_cscope_load' '_cscope_unload' '_cscope_setpath' '_cscope_info' '_cscope_complete' )

_cscope_load ()
{
	DEBUG echo "cscope_load: enter"
	local module="cscope"

	# Load preferences
	
	# Configure module

	DEBUG echo "cscope_load: leave"
}

_cscope_unload ()
{
	local func
	for func in "${__cscope_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_cscope_setpath ()
{
	# CSCOPE Declarations
	export CSCOPE_EDITOR="${EDITOR}"
	export INCLUDEDIRS="" # Colon-separated list of directories to search for #include files
	export SOURCEDIRS="" # Colon-separated list of directories to search for additional source files
	export VPATH="" # Colon-separated list of directories to search. If not set, cscope searches only in the current directory.
}

_cscope_info ()
{
	echo "configures cscope"
}

_cscope_complete()
{
	COMPREPLY=( )
	return 0
}
