#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: git
# Description:
# 	Defines ...
# 	nextline
###############################################################################

#
# Template for new module creation.
# Substitute the new module name for 'git'
# %s/git/newname/gc

__git_dependencies=( 'mbe' )
__git_functions=( '_git_load' '_git_unload' '_git_setpath' '_git_usage' '_git_complete' )

_git_load ()
{
	DEBUG echo "_git_load: enter"
	local module="git"

	# Load preferences
	
	# Configure module

	alias glgga="git log --graph --all --decorate"
	alias glods="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"

	DEBUG echo "_git_load: leave"
}

_git_unload ()
{
	local func
	for func in "${__git_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

_git_setpath ()
{
	return 0
}

_git_usage ()
{
	echo -ne ""
}

_git_complete()
{
	COMPREPLY=( )
	return 0
}
