#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

icscope2_dependencies=( 'mbe' )
icscope2_functions=( 'icscope2_load' 'icscope2_unload' 'icscope2_setpath' 'icscope2_usage' )

icscope2_load ()
{
	DEBUG echo "icscope2_load: enter"
	local module="icscope2"

	# Load preferences
	
	# Configure module

	DEBUG echo "icscope2_load: leave"
}

icscope2_unload ()
{
	local func
	for func in "${icscope2_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

icscope2_setpath ()
{
	if [ -d "/usr/cm/icscope2" ]; then
		if [ -r "/usr/cm/icscope2/bin/icscope2" ]; then
			PATH="/usr/cm/icscope2/bin:${PATH}"
		fi
	fi
}

icscope2_usage ()
{

}
