#!/bin/bash
# vim: set tabstop=2 shiftwidth=2 autoindent smartindent:

#------------------------------------------------------------------------------
# Copyright 2009 Lance W. Feagan
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
#------------------------------------------------------------------------------

###############################################################################
# Module: usrlocalbin
# Description:
# 	Defines ...
# 	nextline
###############################################################################

usrlocalbin_dependencies=( 'mbe' )
usrlocalbin_functions=( 'usrlocalbin_load' 'usrlocalbin_unload' 'usrlocalbin_setpath' 'usrlocalbin_usage' )

usrlocalbin_load ()
{
	DEBUG echo "usrlocalbin_load: enter"
	local module="usrlocalbin"

	# Load preferences
	
	# Configure module

	DEBUG echo "usrlocalbin_load: leave"
}

usrlocalbin_unload ()
{
	local func
	for func in "${usrlocalbin_functions[@]}"; do
		unset "${func}"
	done
	return 0
}

usrlocalbin_setpath ()
{
	# Fix Solaris not having /usr/local/bin, etc in the default PATH
	if [[ "$OSTYPE" == solaris* || "$OSTYPE" == aix* ]]; then
		solaris_bin_paths=("/usr/xpg4/bin" "/usr/xpg6/bin" "/usr/local/bin" "/opt/freeware/bin")
		for i in "${solaris_bin_paths[@]}"; do
			if [ -d "${i}" ]; then
				PATH="${i}:${PATH}"
			fi
		done
		MANPATH="/usr/local/man:/usr/man:${MANPATH}"
	fi
}

usrlocalbin_usage ()
{
	echo "no usage info"
}
